name: Download Directory
description: Downloads a directoy from an artifact based on the upload_directory-action
inputs:
  name:
    description: Name of the artifact to download
    required: true
  destination:
    description: Path to extract the directory
    required: true
runs:
  using: composite
  steps:
    - name: Download directory
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.name }}
        path: ${{ github.workspace }}
    - name: Extract directory
      shell: bash
      run: |
        mkdir -p $DESTINATION
        cd $DESTINATION
        tar -xf $GITHUB_WORKSPACE/${{ inputs.name }}.tar
        rm $GITHUB_WORKSPACE/${{ inputs.name }}.tar
      env:
        DESTINATION: ${{ inputs.destination }}
